### ISSUE TITLE
How to avoid to use `import` command？

### ISSUE THREAD

**Issue by shaoyaoqian** [walpolea/PV#1]
Hello [walpolea](https://github.com/walpolea), thanks for your sharing. Your example is very concise and understandable and I want to know little more.

How to use <script src='path/to/PV.js'></script> to include the file in HTML and use is like this:

```
<script src='path/to/PV.js'><\script>
<script>
PV......
</script>
```

**Comment by walpolea** [comment]
PV is imported as an ES Module with the [`/dist/pv.es.js`](https://github.com/walpolea/PV/blob/main/dist/pv.es.js) file.

If you don't want to use ES Modules, you can use, [`/dist/pv.umd.js`](https://github.com/walpolea/PV/blob/main/dist/pv.umd.js) like this:

```html
<script src="./path/to/pv.umd.js"></script>
<script>
  console.log(PV);

  //PV code here
</script>
```

**Comment by shaoyaoqian** [comment]
Thank you very much.

I tried your demo but both methods didn't work. With the original code, I run these commands:
```
npm run build
nom run dev
```
The error message is :

```
Uncaught SyntaxError: The requested module '/lib/main.js' does not provide an export named 'default' (at index.html:55:10)
```

**Comment by shaoyaoqian** [comment]
When I use umd, the error is 
```
Uncaught TypeError: PV.registerScope is not a function
```
I have changed the code as you described.
https://github.com/walpolea/PV/compare/main...shaoyaoqian:PV:main

**Comment by shaoyaoqian** [comment]
import {PV} from './lib/main.js';

instead of 
import PV from './lib/main.js';
